import {
	DropdownMenuCheckboxItem,
	DropdownMenuContent,
	DropdownMenuGroup,
	DropdownMenuItem,
	DropdownMenuLabel,
	DropdownMenuRadioGroup,
	DropdownMenuRadioItem,
	DropdownMenuRoot,
	DropdownMenuSeparator,
	DropdownMenuSub,
	DropdownMenuSubContent,
	DropdownMenuSubTrigger,
	DropdownMenuTrigger,
	DropdownMenuTriggerIcon,
} from "./components";

export type {
	DropdownMenuCheckboxItemProps,
	DropdownMenuContentProps,
	DropdownMenuGroupProps,
	DropdownMenuItemProps,
	DropdownMenuLabelProps,
	DropdownMenuRadioGroupProps,
	DropdownMenuRadioItemProps,
	DropdownMenuRootProps,
	DropdownMenuSeparatorProps,
	DropdownMenuSubContentProps,
	DropdownMenuSubProps,
	DropdownMenuSubTriggerProps,
	DropdownMenuTriggerIconProps,
	DropdownMenuTriggerProps,
} from "./components";

export const DropdownMenu = {
	Root: DropdownMenuRoot,
	Trigger: DropdownMenuTrigger,
	TriggerIcon: DropdownMenuTriggerIcon,
	Content: DropdownMenuContent,
	Label: DropdownMenuLabel,
	Item: DropdownMenuItem,
	Group: DropdownMenuGroup,
	RadioGroup: DropdownMenuRadioGroup,
	RadioItem: DropdownMenuRadioItem,
	CheckboxItem: DropdownMenuCheckboxItem,
	Sub: DropdownMenuSub,
	SubTrigger: DropdownMenuSubTrigger,
	SubContent: DropdownMenuSubContent,
	Separator: DropdownMenuSeparator,
};
